### ISSUE TITLE
Feature request: dark theme

### ISSUE THREAD

**Issue by Mhowser** [glodanif/BluetoothChat#80]
Please add a dark theme to the app! Or tell me how to do it myself!

**Comment by glodanif** [comment]
Hi, currently, Bluetooth Chat doesn't have a dark theme, but I believe it's something that I can implement in the future. I will put it on my roadmap. Stay tuned.

**Comment by Mhowser** [comment]
Thank you very much for your reply!

**Comment by Mhowser** [comment]
Hi, any progress on this?

**Comment by glodanif** [comment]
@Mhowser I've almost finished it in a dev branch a few weeks ago but I don't have time and motivation for a final push.

**Comment by Mhowser** [comment]
That's great to hear! Don't worry about pushing it of you have more
important tasks to fulfill. Thanks for the update!

**Comment by glodanif** [comment]
Hey @Mhowser, I have finally found free time to complete this feature. 
Night mode is available in [v1.3.2](https://github.com/glodanif/BluetoothChat/releases/tag/v1.3.2)

**Comment by Mhowser** [comment]
Thank you!!
