### ISSUE TITLE
AndroidX incompatibilities

### ISSUE THREAD

**Issue by Carlos2927** [glodanif/BluetoothChat#86]
The project build failed cause by AndroidX incompatibilities
![MJ3}RP`8B`WJ``~$54T )PB](https://user-images.githubusercontent.com/12493233/59813377-c5ac3500-9343-11e9-9c76-260a5a21eb13.png)

**Comment by Carlos2927** [comment]
@glodanif how can i fixed it?

**Comment by glodanif** [comment]
Hi @Carlos2927, do you have these lines:

        android.useAndroidX=true
        android.enableJetifier=true
 in your `gradle.properties` file? Jetifier tool migrates support-library-dependent libraries to rely on the equivalent AndroidX packages instead.
