### ISSUE TITLE
Run problem

### ISSUE THREAD

**Issue by uka7** [glodanif/BluetoothChat#92]
I have this problem when running the project, I have almost tried everything to fix it but nothing happened.
also, I'm not an android developer, I just want to run the project
![Capture](https://user-images.githubusercontent.com/48692755/91344882-3b811b80-e7e7-11ea-98bb-f1692fe07870.JPG)

**Comment by glodanif** [comment]
@uka7 check this issue https://github.com/glodanif/BluetoothChat/issues/86

**Comment by uka7** [comment]
I've seen that but I don't have "gradle.properties" file !

**Comment by glodanif** [comment]
Try creating one.

**Comment by uka7** [comment]
I did, and still nothing changed

**Comment by uka7** [comment]
I've made a new project and copied its gradle.properties file to my project and it worked. 
thank you

**Comment by sughoshn** [comment]
Hi  @uka7  @glodanif ,I got this error could you please help me fix this?
![image](https://user-images.githubusercontent.com/89184002/235479386-92d0173e-4803-43e7-ab88-09370c00acd2.png)
